run:
  name: 'AutoML_v1'
  output_dir: 'reports'
  logging_level: 1

algorithms:
  metrics:
    - 'mse'
    - 'root_mean_squared_error'

  regressor_nn: #Full Connected Neural Network for regressor task
    batch_size: 32
    epochs: 2
    init_lr: 0.0001
    loss: 'mse'
    
    
    architecture:
      type: ''
      input_shape: 
        - 23

      fc:
        - neurons: 64
          activation: 'relu'

        - neurons: 32
          activation: 'relu'

        - neurons: 16
          activation: 'relu'

        - neurons: 2
          activation: 'softmax'

  svm:
    C:
      - 0.1
      - 1
      - 10

    gamma:
      - 1
      - 0.1
      - 0.01

    kernel:
      - 'rbf'
      - 'linear'

  decision_tree:
    max_features:
      - 'sqrt'
      - 'log2'
    
    max_depth:
      - 4
      - 6
      - 8

    criterion:
      - 'gini'
      - 'entropy'

  random_forest:
    n_estimators:
      - 10
      - 50
      - 75
      
    max_features:
      - 'sqrt'
      - 'log2'
    
    max_depth:
      - 4
      - 6
      - 8

    criterion:
      - 'gini'
      - 'entropy'
    
data:
  preprocessing: 'vision' #Options texts, tabular, graphs, etc 
  pipe_details:
    #For vision
    file: 'frames' #Read from frames in dir
    # file: 'video' #Read from video file

    norm: False
    color: 'rgb' #rgb, gray
    resize: [240, 240, 3] #height, width and channels
    resize_aspect_ratio: True
    # - iluminacion: True
    # - filters: ['gaussioan', 'normal', 'etc'] 

    #For text

  augmentation:
    offline:
      #Vision
      horizontal_flip: 1.0 #Probability to do it.
      vertical_flip: 0.0
      # jitter options

    online:
      horizontal_flip: 0.0 #Probability to do it.
      vertical_flip: 0.0
      # jitter options
  
  type: 'videos'
  loader: 'regression'
  source:
    full: 'data/__processed/uci_dataset'
    train: null
    validation: null
    test: null

  annotations:
    external_path: '/home/lara/Documents/tts/ansiedad-vision/mexican_anxiety_detection/data/raw/'
    # external_path: '/home/lara/Documents/tts/ansiedad-vision/tmp_dataset/data/raw/'

    full: 'data/raw/tmp.csv' #Path of csv file with all dataset information
    train: 'data/processed/train.csv'
    test: 'data/processed/test.csv'
    validation: 'data/processed/validation.csv'

    target: 'level' #Name of column target
    splits:
      train: 0.7
      test: 0.3
      validation: 0.0

details:
  description : 'Busqueda del mejor algoritmo utilizando AutoML'
  